
[[exercises]]
name = "simple"
# path = "src/chap_1/exercise_1.rs"
test_mod = "chap_1::exercise_1::tests::test_chap_1"
path = "src/chap_1/exercise_1.rs"
feature = "chap_1_exercise_1"
mode = "test"
hint = """
----------------- hint ! ---------------------------------
Halo2 Exercise 1 :
* Error file: src/chap_1/exercise_1.rs

Try to find the ConstraintNotSatisfied,

In the sentence // vec![(lhs * rhs - out)]

there must be some errors...
----------------------------------------------------------
"""


[[exercises]]
name = "simple-2"
test_mod = "chap_1::exercise_2::tests::test_chap_1"
path = "src/chap_1/exercise_2.rs"
feature = "chap_1_exercise_2"
mode = "test"
hint = """
Halo2 Exercise 2 :
Error file: src/chap_1/exercise_2.rs

Try to find the ConstraintNotSatisfied!!!
"""

[[exercises]]
name = "simple-3"
test_mod = "chap_1::exercise_3::tests::test_chap_1"
path = "src/chap_1/exercise_3.rs"
feature = "chap_1_exercise_3"
mode = "test"
hint = """
Halo2 Exercise 3 :
Error file: src/chap_1/exercise_3.rs

Try to find the ConstraintNotSatisfied!!!
"""

